### ISSUE TITLE
Award / Event Spellings

### ISSUE THREAD

**Issue by kenschenke** [FRCTeam1987/teambroncobots.com#32]
The awards for 2021 and 2022 use the word Region.  They should say Regional.
For the 2018 Dean's list award, it should say "FIRST Dean's List Finalist Award" (word finalist should be in there).

**Comment by kenschenke** [comment]
I realize these mispellings are from the current site.  They should still get corrected though.

**Comment by Mallen220** [comment]
Corrected in most recent push. Thanks.
