### ISSUE TITLE
Typo on sponsor us page

### ISSUE THREAD

**Issue by jschenke488** [FRCTeam1987/teambroncobots.com#33]
![Screenshot_20221003_144653](https://user-images.githubusercontent.com/44783760/193666251-7877778b-e318-4c2c-97db-a43da5f71002.jpg)

**Comment by Mallen220** [comment]
https://github.com/FRCTeam1987/teambroncobots.com/pull/61/commits/281ae167296269e09c097817b2fdeb1e3ae752f5
